### ISSUE TITLE
Packaging for Debian

### ISSUE THREAD

**Issue by knowledgejunkie** [ZanderBrown/nudatus#4]
This is an tracking ticket to follow the Debian Intent to Package (ITP) ticket at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907699.

Nudatus is a recommended dependency of uflash and the Mu editor; I therefore intend to package it for Debian users.

**Comment by knowledgejunkie** [comment]
@ZanderBrown Wondering if you are intending to make a 0.0.4 release include the most recent commits - this would ensure they are included before I upload nudatus to Debian for review/upload.

**Comment by ZanderBrown** [comment]
@knowledgejunkie Done! (sorry for the delay)

**Comment by knowledgejunkie** [comment]
Thank you!

**Comment by knowledgejunkie** [comment]
Update: earlier this week I pushed my packaging of nudatus to the Debian Python Modules repository for review.

**Comment by knowledgejunkie** [comment]
My packaging of nudatus has been reviewed and uploaded to the Debian NEW queue.

**Comment by knowledgejunkie** [comment]
My python-nudatus source package was ACCEPTED into Debian unstable yesterday, so I'm happy for this ticket to be closed. The package will migrate into Debian testing in due course.

**Comment by ZanderBrown** [comment]
Wow!
