### ISSUE TITLE
Inconsistent handling of triple-quote comments

### ISSUE THREAD

**Issue by ScottDWebster** [ZanderBrown/nudatus#7]
A little bit of back story:

When I got my microbit I went through the tutorial on readthedocs.io and tried out most, if not all the code examples, sometimes modifying them and sometimes creating my own code to explore the concepts presented.  I wanted to take the microbit to my local maker space and show some of those demos without having to load them one by one, so I converted many demos to functions and created a simple system to step through the functions using the buttons.  

At some point, I added one or two too many functions and ran out of memory space.  I thought that I had pared it back down to where it was in working condition, but when I tried loading the code up a few days ago, I got memory errors, so I started trying to figure out what I had to do to pare it down.  I was aware of nudatus from having done some hacking on ntoll's uflash previously.

I started looking at the minify option to uflash and was curious to see what the comparison of the before and after states of a file processed with nudatus looked like.  That's when I noticed the inconsistent handling of triple-quote comments.  You'll see in the attached files that some were properly removed while some went untouched.

[Demos.py.txt](https://github.com/ZanderBrown/nudatus/files/2470904/Demos.py.txt)
[Demos-minified.py.txt](https://github.com/ZanderBrown/nudatus/files/2470906/Demos-minified.py.txt)

**Comment by ZanderBrown** [comment]
Hmm, interesting.

Something odd is definitely going on there

**Comment by ZanderBrown** [comment]
Hmm, interesting.

Hopefully resolved by c5c70536a56b360454ef6e747fee674126a560e7

**Comment by ScottDWebster** [comment]
Yep, it's working correctly now (at least for the case that prompted me to report it).
